Revise/remove dumpFiles configuration property/flag
eclipse-kanto/file-upload pull request #65
Opened 2022-10-27 09:17 UTC by daniel-milchev

[#9] Revise/remove dumpFiles configuration property/flag
Changed -dumpFiles flag to DEBUG message

Signed-off-by: Daniel Milchev <fixed-term.daniel.milchev@bosch.io>

2022-10-27 11:56 UTC, e-grigorov requested changes

2022-10-27 11:56 UTC, e-grigorov commented on main.go
> +			log.Fatalln(err)
In the end, it's a validation of the glob filter. Can we find a better place then? What about validation method?

2022-10-27 11:56 UTC, e-grigorov commented on main.go
> +		logger.Debug("No glob filter provided!")
A few lines above, there is info message about the glob filter. Do we need to order the messages?

2022-11-10 11:14 UTC, gboyvalenkov-bosch approved these changes

2022-11-10 11:22 UTC, e-grigorov approved these changes

2022-11-10 11:24 UTC, merged